Search.appendIndex(
    [
                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Buzer",
            "name": "Buzer",
            "summary": "Class\u0020Buzer",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Buzer.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Buzer\u003A\u003AbuildURL\u0028\u0029",
            "name": "buildURL",
            "summary": "Builds\u0020URL\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Buzer.html#method_buildURL"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Buzer\u003A\u003AbuildTitle\u0028\u0029",
            "name": "buildTitle",
            "summary": "Builds\u0020description\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Buzer.html#method_buildTitle"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Buzer\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "Individual\u0020identifier",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Buzer.html#property_identifier"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\DejureOnline",
            "name": "DejureOnline",
            "summary": "Class\u0020DejureOnline",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-DejureOnline.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\DejureOnline\u003A\u003AbuildURL\u0028\u0029",
            "name": "buildURL",
            "summary": "Builds\u0020URL\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-DejureOnline.html#method_buildURL"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\DejureOnline\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "Individual\u0020identifier",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-DejureOnline.html#property_identifier"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\GesetzeImInternet",
            "name": "GesetzeImInternet",
            "summary": "Class\u0020GesetzeImInternet",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-GesetzeImInternet.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\GesetzeImInternet\u003A\u003AbuildURL\u0028\u0029",
            "name": "buildURL",
            "summary": "Builds\u0020URL\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-GesetzeImInternet.html#method_buildURL"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\GesetzeImInternet\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "Individual\u0020identifier",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-GesetzeImInternet.html#property_identifier"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Lexparency",
            "name": "Lexparency",
            "summary": "Class\u0020Lexparency",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Lexparency.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Lexparency\u003A\u003AbuildURL\u0028\u0029",
            "name": "buildURL",
            "summary": "Builds\u0020URL\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Lexparency.html#method_buildURL"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\\Lexparency\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "Individual\u0020identifier",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver-Lexparency.html#property_identifier"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver",
            "name": "Driver",
            "summary": "Class\u0020Driver",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#method___construct"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020a\u0020single\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#method_validate"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003AbuildURL\u0028\u0029",
            "name": "buildURL",
            "summary": "Builds\u0020URL\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#method_buildURL"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003AbuildTitle\u0028\u0029",
            "name": "buildTitle",
            "summary": "Builds\u0020description\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#method_buildTitle"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003AbuildAttributes\u0028\u0029",
            "name": "buildAttributes",
            "summary": "Builds\u0020HTML\u0020attributes\u0020for\u0020corresponding\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#method_buildAttributes"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "Individual\u0020identifier",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#property_identifier"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver\u003A\u003A\u0024library",
            "name": "library",
            "summary": "Available\u0020laws",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Driver.html#property_library"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Factory",
            "name": "Factory",
            "summary": "Class\u0020Factory",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Factory.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Factory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020a\u0020new\u0020\u0027Driver\u0027\u0020instance\u0020for\u0020the\u0020given\u0020type",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Factory.html#method_create"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Factory\u003A\u003A\u0024types",
            "name": "types",
            "summary": "Available\u0020drivers",
            "url": "classes/S1SYPHOS-Gesetze-Drivers-Factory.html#property_types"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz",
            "name": "Gesetz",
            "summary": "Class\u0020Gesetz",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#method___construct"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020a\u0020single\u0020legal\u0020norm\u0020\u0028across\u0020all\u0020providers\u0029",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#method_validate"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "Extracts\u0020legal\u0020norms\u0020as\u0020array\u0020of\u0020strings",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#method_extract"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003Alinkify\u0028\u0029",
            "name": "linkify",
            "summary": "Converts\u0020matched\u0020legal\u0020reference\u0020into\u0020\u0060a\u0060\u0020tag",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#method_linkify"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003Agesetzify\u0028\u0029",
            "name": "gesetzify",
            "summary": "Converts\u0020legal\u0020references\u0020throughout\u0020text\u0020into\u0020\u0060a\u0060\u0020tags",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#method_gesetzify"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003Aroman2arabic\u0028\u0029",
            "name": "roman2arabic",
            "summary": "Converts\u0020roman\u0020numerals\u0020to\u0020arabic\u0020numerals",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#method_roman2arabic"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003A\u0024drivers",
            "name": "drivers",
            "summary": "Available\u0020providers",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#property_drivers"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "Defines\u0020HTML\u0020attributes",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#property_attributes"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Gesetz\u003A\u003A\u0024title",
            "name": "title",
            "summary": "Controls\u0020\u0060title\u0060\u0020attribute",
            "url": "classes/S1SYPHOS-Gesetze-Gesetz.html#property_title"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Traits\\Regex",
            "name": "Regex",
            "summary": "",
            "url": "classes/S1SYPHOS-Gesetze-Traits-Regex.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Traits\\Regex\u003A\u003AgroupMatch\u0028\u0029",
            "name": "groupMatch",
            "summary": "Creates\u0020match\u0020array",
            "url": "classes/S1SYPHOS-Gesetze-Traits-Regex.html#method_groupMatch"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Traits\\Regex\u003A\u003Aanalyze\u0028\u0029",
            "name": "analyze",
            "summary": "Analyzes\u0020a\u0020single\u0020legal\u0020norm",
            "url": "classes/S1SYPHOS-Gesetze-Traits-Regex.html#method_analyze"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Traits\\Regex\u003A\u003A\u0024pattern",
            "name": "pattern",
            "summary": "The\u0020regex,\u0020holding\u0020the\u0020world\u0020together\u0020in\u0020its\u0020inmost\u0020folds",
            "url": "classes/S1SYPHOS-Gesetze-Traits-Regex.html#property_pattern"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Traits\\Regex\u003A\u003A\u0024groups",
            "name": "groups",
            "summary": "Names\u0020for\u0020capturing\u0020groups",
            "url": "classes/S1SYPHOS-Gesetze-Traits-Regex.html#property_groups"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers\\Driver",
            "name": "Driver",
            "summary": "",
            "url": "namespaces/s1syphos-gesetze-drivers-driver.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Drivers",
            "name": "Drivers",
            "summary": "",
            "url": "namespaces/s1syphos-gesetze-drivers.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze",
            "name": "Gesetze",
            "summary": "",
            "url": "namespaces/s1syphos-gesetze.html"
        },                {
            "fqsen": "\\S1SYPHOS",
            "name": "S1SYPHOS",
            "summary": "",
            "url": "namespaces/s1syphos.html"
        },                {
            "fqsen": "\\S1SYPHOS\\Gesetze\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/s1syphos-gesetze-traits.html"
        }            ]
);
